- name: Create folder on Windows server
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_port: 5985
    ansible_user: "{{ dialog_windows_user }}"
    ansible_password: "{{ dialog_windows_password }}"
    ansible_winrm_transport: basic

  tasks:
    - name: Debug connection info
      debug:
        msg:
          - "Running against: {{ inventory_hostname }}"
          - "User: {{ ansible_user }}"
