---
- name: Create folder on Windows server
  hosts: all
  gather_facts: no
  vars:
    target_folder: "C:\\TestFolder"

  tasks:
    - name: Show input variables
      debug:
        msg:
          - "windows_user: {{ windows_user | default('NOT SET') }}"
          - "windows_password defined?: {{ windows_password is defined }}"
          - "windows_host: {{ windows_host | default('NOT SET') }}"

    - name: Map custom vars to Ansible connection vars
      set_fact:
        ansible_user: "{{ windows_user }}"
        ansible_password: "{{ windows_password }}"
        ansible_host: "{{ windows_host | default(inventory_hostname) }}"

    - name: Show mapped Ansible connection variables
      debug:
        msg:
          - "ansible_user: {{ ansible_user }}"
          - "ansible_password defined?: {{ ansible_password is defined }}"
          - "ansible_host: {{ ansible_host }}"

    - name: Ensure folder exists
      win_file:
        path: "{{ target_folder }}"
        state: directory

