- hosts: all
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_port: 5985
    ansible_user: "{{ dialog_windows_user }}"
    ansible_password: "{{ dialog_windows_password }}"
  tasks:
    - name: Show user
      debug:
        msg: "User provided: {{ dialog_windows_user }}"

    - name: Show password (for debugging only!)
      debug:
        msg: "Password provided: {{ dialog_windows_password }}"
      no_log: false   # set to true once you confirm it's working

