- name: Create folder on Windows server
  hosts: all
  gather_facts: no

  vars:
    ansible_connection: winrm
    ansible_port: 5985
    ansible_user: "{{ dialog_windows_user }}"
    ansible_password: "{{ dialog['password::dialog_windows_password'] }}"
    ansible_winrm_transport: basic

  tasks:
    - name: Debug vars
      debug:
        msg:
          - "User: {{ dialog_windows_user | default('NOT SET') }}"
          - "Password defined: {{ 'YES' if (dialog['password::dialog_windows_password'] is defined and dialog['password::dialog_windows_password']|length > 0) else 'NO' }}"
          - "Host: {{ dialog_windows_host | default('NOT SET') }}"

    - name: Create folder under C:\
      win_file:
        path: C:\TestFolder
        state: directory
