- name: Create folder on Windows server
  hosts: all
  vars:
    ansible_user: "{{ windows_user }}"
    ansible_password: "{{ windows_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_port: 5985

  tasks:
    - name: Create folder under C:\
      win_file:
        path: C:\TestFolder
        state: directory
      






