- name: Create folder on Windows server
  hosts: windows
  vars:
    ansible_user: "{{ windows_user }}"
    ansible_password: "{{ windows_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_port: 5985

  tasks:
    - name: Create test file on Windows
    win_copy:
    content: "Hello from Ansible"
    dest: C:\\Temp\\test.txt



