- name: Create folder on Windows server
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_port: 5985
    ansible_user: "{{ windows_user }}"
    ansible_password: "{{ password }}"
    ansible_winrm_transport: basic

  tasks:
    - name: Debug all vars (excluding huge ones)
      debug:
        var: hostvars[inventory_hostname]
    - name: Create folder under C:\
      win_file:
        path: C:\TestFolder
        state: directory


