- hosts: all
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_port: 5985
    ansible_user: "{{ windows_user }}"
    ansible_password: "{{ windows_password }}"
  tasks:
    - name: Show Windows user
      debug:
        msg: "User = {{ ansible_user }}"

    - name: Show Windows password
      debug:
        msg: "Password = {{ ansible_password }}"
      no_log: false   # ⚠️ remove this once tested

