- name: Create folder on Windows server
  hosts: all
  gather_facts: no

  vars:
    ansible_connection: winrm
    ansible_port: 5985
    ansible_user: "{{ dialog_windows_user }}"
    ansible_password: "{{ dialog_windows_password }}"
    ansible_winrm_transport: basic

  tasks:
    - name: Debug all input vars
      debug:
        msg:
          - "Windows Host: {{ windows_host | default('NOT SET') }}"
          - "Windows User: {{ windows_user | default('NOT SET') }}"
          - "Windows Password defined: {{ 'YES' if (windows_password is defined and windows_password|length > 0) else 'NO' }}"

    - name: Debug connection info
      debug:
        msg:
          - "Running against: {{ inventory_hostname }}"
          - "User: {{ ansible_user }}"
          - "Password defined: {{ 'YES' if (ansible_password is defined and ansible_password|length > 0) else 'NO' }}"

    - name: Create folder under C:\
      win_file:
        path: C:\TestFolder
        state: directory

