- name: Create folder on Windows server
  hosts: "{{ dialog_windows_host }}"
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_port: 5985
    ansible_user: "{{ dialog_windows_user }}"
    ansible_password: "{{ dialog_windows_password }}"
    ansible_winrm_transport: basic

  tasks:
    - name: Debug vars
      debug:
        msg:
          - "Target: {{ inventory_hostname }}"
          - "User: {{ ansible_user }}"
          - "Password passed: {{ ansible_password | default('NOT SET') }}"
