- name: Create folder on Windows server
  hosts: all
  gather_facts: no

  vars:
    # Map from dialog variables
    windows_host: "{{ dialog_windows_host }}"
    windows_user: "{{ dialog_windows_user }}"
    windows_password: "{{ dialog_windows_password }}"

    # Connection settings
    ansible_connection: winrm
    ansible_port: 5985
    ansible_user: "{{ windows_user }}"
    ansible_password: "{{ windows_password }}"
    ansible_winrm_transport: basic

  tasks:
    - name: Dump all vars (searching for dialog_)
      debug:
        var: vars
      tags: always
    - name: Debug connection info
      debug:
        msg:
          - "Running against: {{ inventory_hostname }}"
          - "User: {{ ansible_user }}"
          - "Password defined: {{ 'YES' if (ansible_password is defined and ansible_password|length > 0) else 'NO' }}"

    - name: Create folder under C:\
      win_file:
        path: C:\TestFolder
        state: directory

