- name: Test Create Folder on Windows
  hosts: all
  vars:
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: basic
  tasks:
    - name: Create folder under C:\
      win_file:
        path: C:\{{ folder_name }}
        state: directory




