- hosts: all
  vars:
    ansible_user: "{{ dialog_windows_user }}"
    ansible_password: "{{ dialog_windows_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_port: 5985

  tasks:
    - name: Debug connection info
      debug:
        msg:
          - "Running against: {{ inventory_hostname }}"
          - "User: {{ ansible_user }}"
          - "Password defined: {{ ansible_password is defined }}"

    - name: Create folder under C:\
      win_file:
        path: C:\TestFolder
        state: directory
