- name: Test Windows Folder Creation
  hosts: all
  vars:
    ansible_connection: winrm
    ansible_host: 192.168.1.189      # change to your Windows server IP
    ansible_port: 5985
    ansible_user: Administrator
    ansible_password: P@ssw0rd
    ansible_winrm_transport: basic
  tasks:
    - name: Create folder under C:\
      win_file:
        path: C:\TestFolder
        state: directory
